language: java
jdk: -oraclejdk15
sudo: false

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

nitifications:
  email:
    recipients:
      - frowzygleb@gmail.com
    on_success: never
    on_failure: always