CREATE TABLE IF NOT EXISTS users
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    username VARCHAR(128) NOT NULL ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    first_name VARCHAR(128) NOT NULL ,
    last_name VARCHAR(128) NOT NULL ,
    password VARCHAR(255) NOT NULL ,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE'
) engine = InnoDB;
