CREATE TABLE IF NOT EXISTS files
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    name VARCHAR(255) NOT NULL UNIQUE ,
    extension VARCHAR(128) NOT NULL ,
    size BIGINT NOT NULL ,
    bucket VARCHAR(128) ,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' ,
    user_id BIGINT NOT NULL ,
    FOREIGN KEY(user_id) REFERENCES users(id)
) engine = InnoDB;