CREATE TABLE IF NOT EXISTS accounts
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    name VARCHAR(128) NOT NULL UNIQUE ,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' ,
    user_id BIGINT NOT NULL ,
    FOREIGN KEY(user_id) REFERENCES users(id)
) engine = InnoDB;
